name = "GitHubAppTokens"
uuid = "065bf76e-ca52-408e-80ac-b2f947d0e344"
version = "0.0.1"
authors = "Nishanth H. Kottary <nishanth@juliahub.com>"
keywords = ["github", "app", "token"]
license = "MIT"
desc = "Julia client access token fetcher for GitHub apps"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Retry = "20febd7b-183b-5ae2-ac4a-720e7ce64774"

[compat]
Dates = "1.11.0"
GitHub = "5.9.0"
HTTP = "1"
JSON = "0.21.4"
LRUCache = "1.6.2"
Retry = "0.4.1"
Test = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[targets]
test = ["Test", "TimeZones"]
